// <auto-generated />
namespace CtrlPonto.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class modelUp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modelUp));
        
        string IMigrationMetadata.Id
        {
            get { return "201906071336492_modelUp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
