// <auto-generated />
namespace CtrlPonto.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class changeTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201906101403028_changeTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
