// <auto-generated />
namespace CtrlPonto.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class deleteAlter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteAlter));
        
        string IMigrationMetadata.Id
        {
            get { return "201906051925152_deleteAlter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
